name: 'oxs-package-upload'
description: 'Uploads a zip file to a Web API endpoint'

branding:
  icon: upload
  color: 'blue'

inputs:
  payload-path:
    description: 'The path to the directory containing payload JSON files'
    required: true
  api-url:
    description: 'The Web API endpoint URL'
    required: true
  api-token:
    description: 'The API authorization token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload JSON files to API
      env:
        API_URL: ${{ inputs.api-url }}
        API_TOKEN: ${{ inputs.api-token }}
        PAYLOAD_PATH: ${{ inputs.payload-path }}
      shell: bash
      run: |
        if [ ! -d "$PAYLOAD_PATH" ]; then
          echo "Payload directory not found: $PAYLOAD_PATH"
          exit 1
        fi

        json_files=($(find "$PAYLOAD_PATH" -maxdepth 1 -type f -name '*.json'))
        
        if [ ${#json_files[@]} -eq 0 ]; then
          echo "No JSON files found in directory: $PAYLOAD_PATH"
          exit 1
        fi

        for file in "${json_files[@]}"; do
          echo "Uploading $file..."
          curl -X POST "$API_URL" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d @"$file" \
            -v
        done
