name: 'oxs-package-upload'
description: 'Uploads a zip file to a Web API endpoint'

branding:
  icon: upload
  color: 'blue'

inputs:
  payload-path:
    description: 'The path to the payload JSON file to upload'
    required: true
  api-url:
    description: 'The Web API endpoint URL'
    required: true
  api-token:
    description: 'The API authorization token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload to API
      env:
        API_URL: ${{ inputs.api-url }}
        API_TOKEN: ${{ inputs.api-token }}
      shell: bash
      run: |
        curl -X POST "$API_URL" \
          -H "Authorization: Bearer $API_TOKEN" \
          -H "Content-Type: application/json" \
          -d @${{ inputs.payload-path }} 
    
